In [16]:
from PIL import Image
import numpy as np
img = Image.open('/Users/zhangjiayun/Downloads/10.35097-538/data/dataset/orthomosaic/CFB153_ortho.tif')
height_img = Image.open('/Users/zhangjiayun/Downloads/10.35097-538/data/dataset/nDSM/nDSM_CFB153.tif')
# use chunk size 1024x1024
chunk_size = 1024 

width, height = img.size
print(width)
print(height)

# calculate how many chunks do we need
x_chunks = width // chunk_size + bool(width % chunk_size)
y_chunks = height // chunk_size + bool(height % chunk_size)
print(x_chunks)
print(y_chunks)
# for y in range(y_chunks):
#     for x in range(x_chunks):
for y in range(1):
    for x in range(3):
        left = x * chunk_size
        upper = y * chunk_size
        right = min(left + chunk_size, width)
        lower = min(upper + chunk_size, height)
        
        chunk = img.crop((left, upper, right, lower))
        chunk_height = height_img.crop((left, upper, right, lower))
        data_img = np.array(chunk)
        data_height = np.array(chunk_height)
        chunk.show()
        chunk_height.show()
        break
print(data_img)

14570
14570
15
15
[[-3.4000000e+38 -3.4000000e+38 -3.4000000e+38 ... -3.4000000e+38
  -3.4000000e+38 -3.4000000e+38]
 [-3.4000000e+38 -3.4000000e+38 -3.4000000e+38 ... -3.4000000e+38
  -3.4000000e+38 -3.4000000e+38]
 [-3.4000000e+38 -3.4000000e+38 -3.4000000e+38 ... -3.4000000e+38
  -3.4000000e+38 -3.4000000e+38]
 ...
 [ 2.3373779e+01  2.3823364e+01  2.4091187e+01 ...  1.6829346e+01
  -3.4000000e+38 -3.4000000e+38]
 [ 2.3266113e+01  2.3313110e+01  2.3687988e+01 ... -3.4000000e+38
  -3.4000000e+38 -3.4000000e+38]
 [ 2.3214233e+01  2.3204956e+01  2.3272339e+01 ... -3.4000000e+38
  -3.4000000e+38 -3.4000000e+38]]


In [15]:
data_height = data_height /(np.max(data_height) - np.min(data_height)) 

AttributeError: 'numpy.ndarray' object has no attribute 'show'

In [17]:
print(data_img)

[[[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [ 32  53  42 255]
  [ 31  53  42 255]
  [ 29  51  40 255]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [ 33  55  43 255]
  [ 29  52  37 255]
  [ 30  48  38 255]]

 [[  0   0   0   0]
  [  0   0   0   0]
  [  0   0   0   0]
  ...
  [ 33  53  42 255]
  [ 28  50  35 255]
  [ 30  47  36 255]]

 ...

 [[ 83 120  72 255]
  [ 84 119  73 255]
  [ 85 121  73 255]
  ...
  [ 17  37  29 255]
  [ 17  37  29 255]
  [ 18  38  31 255]]

 [[ 82 118  70 255]
  [ 82 118  70 255]
  [ 82 118  70 255]
  ...
  [ 17  37  29 255]
  [ 17  37  30 255]
  [ 17  38  31 255]]

 [[ 81 116  69 255]
  [ 81 116  69 255]
  [ 80 116  69 255]
  ...
  [ 16  37  30 255]
  [ 17  38  32 255]
  [ 17  39  32 255]]]
